FORMAT: 1A
HOST: http://spiderlog.net

# SpiderLog

Provides services for the Pider Log app family, recording the world's spider sightings

#Group Spiders
Access to Spider resources

## My Spiders [/spiders{?page,size}]
### Get all my spider sigtings [GET]

+Parameters
    + page (required, number, 1 )...  page number
    + size (required, number, 10 )... page size
    
+Request

    +Header
    
        Authorization: Basic dXNlcjpwYXNzd29yZA==
        
+ Response 200 (application/json)

        {
            "page" : 
            {  
                "number" : 1,
                "size" : 10,
              "totalPages": 20
              },
              "spiders" :
            [    
                {  
                    "sightedat" : "2014-08-29To7:00",
                    "description" : "Spider I saw at the office"
                }
            ]
        }